name: enver

services:
  enver:
    build:
      context: .
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  redis:
    image: redis:7.4.2-alpine3.21
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 30s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  clickhouse:
    image: clickhouse:25.3.2
    ports:
      - "8124:8123"
      # - "9000:9000"
    hostname: clickhouse
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    cap_add:
        - SYS_NICE
        - NET_ADMIN
        - IPC_LOCK
    restart: unless-stopped
    volumes:
        - clickhouse_data:/var/lib/clickhouse/
        - clickhouse_logs:/var/log/clickhouse-server/
    environment:
        CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        CLICKHOUSE_DB: ${CLICKHOUSE_DB}
        CLICKHOUSE_USER: ${CLICKHOUSE_USER}
        # CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
    redis_data:
    clickhouse_data:
    clickhouse_logs:

networks:
    default:
        name: enver
        external: true